controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/kernel.php
    type: annotation
api_login_check:
    path: /api/login_check
api_refresh_token:
    path: /api/token/refresh
api_token_invalidate:
    path: /api/token/invalidate
